export type Lang = "en" | "af";

type Entry = { en: string; af: string };

export const DICT = {
  nav_home: { en: "Home", af: "Tuis" },
  nav_story: { en: "Us Through the Years", af: "Ons Deur die Jare" },
  nav_day: { en: "Wedding Day", af: "Troudag" },
  nav_travel: { en: "Travel & Stay", af: "Reis & Verblyf" },
  nav_party: { en: "Wedding Party", af: "Gevolg" },
  nav_dress: { en: "Dress Code", af: "Kleredrag" },
  nav_games: { en: "BrooksWay", af: "BrooksWay" },
  nav_registry: { en: "Registry", af: "Geskenke" },
  nav_faq: { en: "FAQ", af: "Vrae" },
  nav_contact: { en: "Contact", af: "Kontak" },
  nav_rsvp: { en: "RSVP", af: "RSVP" },
  bride_dashboard: { en: "Bride Dashboard", af: "Bruid se Paneel" },
  hero_eyebrow: { en: "We're getting married", af: "Ons gaan trou" },
  wedding_date: { en: "5 December 2026", af: "5 Desember 2026" },
  wedding_date_venue: { en: "5 December 2026 · Bona Bona Game Reserve", af: "5 Desember 2026 · Bona Bona Game Reserve" },
  loading_wedding_of: { en: "The Wedding Of", af: "Die Troue Van" },
  home_countdown_caption: { en: "Counting down to forever", af: "Aftel na vir ewig" },
  home_cant_wait: { en: "We can't wait", af: "Ons kan nie wag nie" },
  home_see_you_there: { en: "See you there", af: "Sien jou daar" },
  scroll: { en: "Scroll", af: "Blaai af" },
  cd_days: { en: "Days", af: "Dae" },
  cd_hours: { en: "Hours", af: "Ure" },
  cd_minutes: { en: "Minutes", af: "Minute" },
  cd_seconds: { en: "Seconds", af: "Sekondes" },
  fact_when: { en: "When", af: "Wanneer" },
  fact_where: { en: "Where", af: "Waar" },
  fact_dress: { en: "Dress", af: "Drag" },
  fact_dress_v: { en: "Formal", af: "Formeel" },
  fact_dress_sub: { en: "Chocolate tones", af: "Sjokoladetinte" },
  fact_when_sub: { en: "Saturday · 16:00", af: "Saterdag · 16:00" },
  fact_when_v: { en: "5 Dec 2026", af: "5 Des 2026" },
  fact_where_sub: { en: "North West", af: "Noordwes" },
  welcome_default: {
    en: 'After seven years and one very good "yes", we cannot wait to gather everyone we love in one place. Thank you for being part of our story — let us celebrate.',
    af: "Na sewe jaar en een baie goeie “ja” kan ons nie wag om almal vir wie ons lief is op een plek bymekaar te maak nie. Dankie dat jy deel is van ons storie — kom ons vier fees.",
  },
  rsvp_by: { en: "Kindly respond by 1 November 2026", af: "Laat weet ons asseblief teen 1 November 2026" },
  rsvp_find_intro: {
    en: "Find your invitation by typing your name. We'll bring up your whole party so you can respond for everyone at once.",
    af: "Tik jou naam om jou uitnodiging te kry. Ons wys jou hele groep, sodat jy sommer vir almal gelyk kan antwoord.",
  },
  rsvp_search_ph: { en: "Type your first or last name…", af: "Tik jou voor- of van…" },
  rsvp_your_party: { en: "Your party", af: "Jou groep" },
  rsvp_tap_attend: {
    en: "Mark yes or no for each person in your party.",
    af: "Merk ja of nee vir elkeen in jou groep.",
  },
  rsvp_check_all: { en: "Mark everyone attending", af: "Merk almal as woon by" },
  rsvp_mark_all_no: { en: "Mark everyone can't attend", af: "Merk almal as kan nie kom nie" },
  rsvp_attending: { en: "Attending", af: "Woon by" },
  rsvp_not_attending: { en: "Can't attend", af: "Kan nie kom nie" },
  rsvp_tap_to_add: { en: "Tap to add", af: "Tik om by te voeg" },
  rsvp_continue: { en: "Continue →", af: "Gaan voort →" },
  rsvp_answer_all: { en: "Please mark yes or no for everyone in your party.", af: "Merk asseblief ja of nee vir almal in jou groep." },
  rsvp_search_other: { en: "← Search a different name", af: "← Soek 'n ander naam" },
  rsvp_send: { en: "Send our RSVP", af: "Stuur ons RSVP" },
  rsvp_thanks: { en: "Thank you for celebrating with us.", af: "Dankie dat jy saam met ons kom fees vier." },
  rsvp_respond_another: { en: "Respond for another family", af: "Antwoord vir 'n ander gesin" },
  footer_made: { en: "Made with love · December 2026", af: "Met liefde gemaak · Desember 2026" },
  party_title: { en: "The Wedding Party", af: "Gevolg" },
  party_sub: { en: "The dearest people standing beside us.", af: "Die mense wat die naaste aan ons harte is." },
  tab_groomsmen: { en: "The Groomsmen", af: "Die Strooijonkers" },
  tab_bridesmaids: { en: "The Bridesmaids", af: "Die Strooimeisies" },
  role_bestman: { en: "Best Man", af: "Seremoniemeester" },
  role_groomsman: { en: "Groomsman", af: "Strooijonker" },
  role_moh: { en: "Maid of Honour", af: "Hoofstrooimeisie" },
  role_bridesmaid: { en: "Bridesmaid", af: "Strooimeisie" },
  goh_tag: { en: "A very important guest", af: "'n Baie spesiale gas" },
  goh_role: { en: "Chief Good Boy", af: "Hoof Soet Seun" },
  couple_bio: {
    en: 'Seven years, a thousand small moments, and one very good "yes". We cannot wait to celebrate with the people we love most.',
    af: 'Sewe jaar, duisend klein oomblikke, en een baie goeie "ja". Ons kan nie wag om saam met die mense vir wie ons die meeste lief is te vier nie.',
  },
  banking_title: { en: "Banking Details", af: "Bankbesonderhede" },
  day_order: { en: "Order of the Day", af: "Program vir die Dag" },
  day_addcal: { en: "＋ Add to Calendar", af: "＋ Voeg by Kalender" },
  day_directions: { en: "Directions & Parking", af: "Aanwysings & Parkering" },
  travel_eyebrow: { en: "Plan your stay", af: "Beplan jou verblyf" },
  travel_title: { en: "Travel & Accommodation", af: "Reis & Verblyf" },
  meet_couple: { en: "Meet the couple", af: "Ontmoet die paartjie" },
  gifts_eyebrow: { en: "Gifts", af: "Geskenke" },
  registry_title: { en: "Registry", af: "Geskenke" },
  faq_eyebrow: { en: "Good to know", af: "Goed om te weet" },
  faq_title: { en: "FAQ", af: "Algemene Vrae" },
  contact_eyebrow: { en: "We're here to help", af: "Ons help graag" },
  contact_title: { en: "Contact", af: "Kontak" },
  rsvp_details: { en: "A few details", af: "'n Paar besonderhede" },
  rsvp_menu: { en: "Buffet menu — dietary needs per guest", af: "Buffet-spyskaart — laat weet ons van dieetbehoeftes" },
  rsvp_allergies: { en: "Any allergies or dietary notes", af: "Enige allergieë of dieetnotas" },
  rsvp_song: { en: "Song request", af: "Liedjie-versoek" },
  rsvp_artist: { en: "Artist", af: "Kunstenaar" },
  rsvp_songname: { en: "Song name", af: "Liedjienaam" },
  rsvp_message: { en: "A message for the couple", af: "'n Boodskap vir die paartjie" },
  rsvp_mobile: { en: "Mobile", af: "Selfoon" },
  rsvp_email: { en: "Email", af: "E-pos" },
  rsvp_back: { en: "← Back", af: "← Terug" },
  rsvp_decline_heading: { en: "So sorry to miss it", af: "Jammer om dit te mis" },
  rsvp_decline_sub: {
    en: "We'll miss having you there — let us know below, and leave a message if you'd like.",
    af: "Ons sal jou mis — laat weet ons hieronder, en los gerus 'n boodskap.",
  },
  rsvp_send_decline: { en: "Send our response", af: "Stuur ons antwoord" },
  rsvp_declined_thanks: { en: "Thank you for letting us know.", af: "Dankie dat jy ons laat weet het." },
  day_eyebrow: { en: "Saturday", af: "Saterdag" },
  day_title: { en: "The Wedding Day", af: "Die Troudag" },
  story_eyebrow: { en: "Through the years", af: "Deur die jare" },
  story_title: { en: "Us Through the Years", af: "Ons Deur die Jare" },
  story_sub: {
    en: "Seven years, a thousand small moments, and one very good answer to one very important question.",
    af: "Sewe jaar, duisend klein oomblikke, en een baie goeie antwoord op een baie belangrike vraag.",
  },
  party_eyebrow: { en: "Celebrating with us", af: "Vier saam met ons" },
  rsvp_nomatch: {
    en: "No match found. Check spelling or contact the couple — your name may be under another family member.",
    af: "Geen passing gevind nie. Kontroleer die spelling of kontak die paartjie — jou naam is dalk onder 'n ander familielid.",
  },
  rsvp_confirm_to: { en: "A confirmation will be sent to", af: "'n Bevestiging sal gestuur word na" },
  travel_sub: {
    en: "A handpicked range of places to stay, all within easy reach of",
    af: "'n Paar uitgesoekte plekke om te bly, almal maklik bereikbaar vanaf",
  },
  book_cta: { en: "View & Book ↗", af: "Bekyk & Bespreek ↗" },
  dress_kicker: { en: "What to wear", af: "Wat om te dra" },
  dress_title: { en: "Dress Code", af: "Kleredrag" },
  dress_intro: {
    en: "Formal, in earthy chocolate tones. Think elegant floor-length dresses and suits in rich browns — let's wear the palette together.",
    af: "Formeel in aardse sjokoladebruin. Dink elegante lang rokke en pakke in ryk bruintinte — laat ons saam die palet dra.",
  },
  dress_note: {
    en: "Please avoid white, ivory and bright neons — those are reserved for the bride and the camera.",
    af: "Vermy asseblief wit, ivoor en helder neon — dit is vir die bruid en die kamera gereserveer.",
  },
  registry_message: {
    en: "Your presence is honestly our biggest gift! Flights, accommodation, and let's not even get started on petrol prices. We can't thank you enough. If you do feel like giving us a wedding gift though, we won't put up a fight ;)",
    af: "Jou teenwoordigheid is werklik ons grootste geskenk! Vliegtuig kaartjies, verblyf en om nie eens van petrol pryse te praat nie. Ons kan nie genoeg dankie sê nie. As jy wel voel dat jy 'n trougeskenk sal wil gee sal ons nie verder stry nie ;)",
  },

  // BrooksWay (the prediction game) — guest-facing UI chrome.
  bw_tagline: { en: "The Wedding Prediction Game", af: "Die Troue-voorspellingspel" },
  bw_live: { en: "Live", af: "Regstreeks" },
  bw_coming_soon: { en: "Coming Soon", af: "Binnekort" },
  bw_intro: {
    en: "Two games, two bar tabs. Make your predictions, pay R50 a slip, and follow your own calls live through the day. Buy as many slips as you like.",
    af: "Twee speletjies, twee kroegrekeninge. Maak jou voorspellings, betaal R50 per strokie, en volg jou eie voorspellings regstreeks deur die dag. Koop soveel strokies as wat jy wil.",
  },
  bw_ceremony_title: { en: "Ceremony Predictions", af: "Seremonie-voorspellings" },
  bw_ceremony_kicker: { en: "Game One", af: "Speletjie Een" },
  bw_reception_title: { en: "Reception Predictions", af: "Onthaal-voorspellings" },
  bw_reception_kicker: { en: "Game Two", af: "Speletjie Twee" },
  bw_revealed: { en: "Revealed", af: "Onthul" },
  bw_coming_soon_badge: { en: "Coming soon", af: "Binnekort" },
  bw_predictions_stat: { en: "Predictions", af: "Voorspellings" },
  bw_bartab_stat: { en: "Bar Tab", af: "Kroegrekening" },
  bw_build_slip: { en: "Build Slip", af: "Bou Strokie" },
  bw_my_slips: { en: "My Slips", af: "My Strokies" },
  bw_not_open_yet: { en: "Predictions open closer to the day — check back soon.", af: "Voorspellings open nader aan die dag — kom kyk gerus later weer." },
  bw_winners_view: { en: "🎉 Winners announced — view", af: "🎉 Wenners aangekondig — bekyk" },
  bw_name_placeholder: { en: "Your name (for the slip)", af: "Jou naam (vir die strokie)" },
  bw_slip_stake: { en: "Slip Stake", af: "Strokie-inset" },
  bw_winner_takes: { en: "Winner takes", af: "Wenner kry" },
  bw_pay_btn: { en: "Pay R50 with PayFast", af: "Betaal R50 met PayFast" },
  bw_redirecting: { en: "Redirecting to checkout…", af: "Herlei na uitklaring…" },
  bw_back_to_games: { en: "← Back to games", af: "← Terug na speletjies" },
  bw_test_mode: { en: "Test mode — PayFast sandbox checkout (no real charge). See README.", af: "Toetsmodus — PayFast-toetsomgewing (geen werklike heffing nie). Sien README." },
  bw_cancelled_title: { en: "Payment cancelled", af: "Betaling gekanselleer" },
  bw_cancelled_sub: {
    en: "No charge was made. Your slip is saved — you can pay for it any time from My Slips.",
    af: "Geen heffing is gemaak nie. Jou strokie is gestoor — jy kan enige tyd daarvoor betaal via My Strokies.",
  },
  bw_confirming_title: { en: "Confirming payment…", af: "Bevestig betaling…" },
  bw_confirming_sub: { en: "This usually takes a few seconds. Hang tight.", af: "Dit neem gewoonlik net 'n paar sekondes. Hou vas." },
  bw_confirmed_title: { en: "Slip Confirmed", af: "Strokie Bevestig" },
  bw_confirmed_sub: { en: "Payment received · R50.00. Your predictions are locked in.", af: "Betaling ontvang · R50.00. Jou voorspellings is vasgelê." },
  bw_view_my_slips: { en: "View My Slips", af: "Bekyk My Strokies" },
  bw_back_to_games_btn: { en: "Back to Games", af: "Terug na Speletjies" },
  bw_myslips_intro: {
    en: "Slips you've built on this device. ✔ correct · ✖ missed · ⏳ still to come.",
    af: "Strokies wat jy op hierdie toestel gebou het. ✔ reg · ✖ verkeerd · ⏳ nog te kom.",
  },
  bw_paid: { en: "Paid", af: "Betaal" },
  bw_awaiting_payment: { en: "Awaiting payment", af: "Wag vir betaling" },
  bw_no_slips: { en: "No slips yet. Build one to get in the game.", af: "Nog geen strokies nie. Bou een om deel te neem." },
  bw_view_arrow: { en: "View →", af: "Bekyk →" },
  bw_all_my_slips: { en: "← All my slips", af: "← Al my strokies" },
  bw_your_call: { en: "Your call:", af: "Jou keuse:" },
  bw_actual: { en: "Actual:", af: "Werklik:" },
  bw_winners_suffix: { en: "Winners", af: "Wenners" },
  bw_winners_sub: { en: "Congratulations to whoever called it best.", af: "Geluk aan wie ook al die beste voorspel het." },
  bw_footer: { en: "For entertainment only · No real gambling · 18+", af: "Slegs vir vermaak · Geen werklike dobbelary nie · 18+" },
} as const satisfies Record<string, Entry>;

export type DictKey = keyof typeof DICT;

export function t(key: DictKey, lang: Lang): string {
  return DICT[key][lang];
}
